<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net4.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<EnableDefaultItems>false</EnableDefaultItems>
		<AssemblyName>FNA</AssemblyName>
		<RootNamespace>Microsoft.Xna.Framework</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>4</LangVersion>
	</PropertyGroup>
	<PropertyGroup>
		<FNASettingsPropsFilePath>$(SolutionDir)FNA.Settings.props</FNASettingsPropsFilePath>
	</PropertyGroup>
	<Import Project="$(FNASettingsPropsFilePath)" Condition="Exists('$(FNASettingsPropsFilePath)')" />
	<Target Name="ValidatePropsFilePath" BeforeTargets="BeforeBuild">
		<Message Importance="High" Text="No property overrides found at '$(FNASettingsPropsFilePath)'" Condition="!Exists('$(FNASettingsPropsFilePath)')" />
		<Message Importance="High" Text="Loaded property overrides from '$(FNASettingsPropsFilePath)'" Condition="Exists('$(FNASettingsPropsFilePath)')" />
	</Target>
	<ItemGroup>
		<None Include="app.config" />
	</ItemGroup>
	<Import Project="FNA.projitems" />
</Project>
